site_name: Kraków water quality monitoring
docs_dir: docs
repo_url: https://github.com/Sc00ra/K_WQ

copyright: Skóra/Firek

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'light blue'

plugins:
  - search
  - mkdocs-material
  - mkdocs-mermaid2-plugin  # for diagrams


nav:
  - Introduction: index.md
  