site_name: Kraków water quality monitoring
docs_dir: docs
repo_url: https://github.com/Sc00ra/K_WQ

copyright: Skóra/Firek

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  logo: ./docs_images/satellite.png
  favicon: ./docs_images/satellite.png

nav:
  - Abstract: index.md
  - WaterQuality:
      - CDOM: waterquality/cdom.md
      - DOM: waterquality/doc.md
      - Chlorophyll-a: waterquality/chlorophyl.md
      - Turbidity: waterquality/turbidity.md
  - Superresolution: superres.md
  
      